image: jakzal/phpqa:php8.0

before_script:
    - composer install

cache:
    paths:
        - vendor/

stages:
    - SecurityChecker
    - CodingStandards
    - UnitTests

security-checker:
    stage: SecurityChecker
    script:
        - local-php-security-checker  --path=./composer.lock
    allow_failure: false

phpcs:
    stage: CodingStandards
    script:
        - phpcs -v --standard=PSR12 --ignore=./src/Kernel.php ./src
    allow_failure: false

phpstan:
    stage: CodingStandards
    script:
        - phpstan analyse ./src
    allow_failure: false

twig-lint:
    stage: CodingStandards
    script:
        - twig-lint lint ./templates
    allow_failure: false

phpunit:
    image: php:8.0-apache
    stage: UnitTests
    services:
        - name: mysql:8.0
          alias: mysql
    variables:
        MY_DB_ROOT_PWD: pass_test
        MY_DB_USER: myapptest
        MY_DB_PWD: myapptest
        MY_DB_NAME: myapptest_test
        DATABASE_URL: mysql://${MY_DB_USER}:${MY_DB_PWD}@mysql:3306/${MY_DB_NAME}?serverVersion=8&charset:utf8mb4

    before_script:
        - apt-get update && apt-get install -y git libzip-dev
        - curl -sSk https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar /usr/local/bin/composer
        - docker-php-ext-install mysqli pdo pdo_mysql zip
        - php bin/console doctrine:database:drop --force --env=test
        - php bin/console doctrine:database:create --env=test
        - php bin/console doctrine:migration:migrate --env=test --no-interaction
    script:
        - php bin/phpunit
    allow_failure: false
